### ISSUE TITLE
"No signature for method" error when adding proguard config for release

### ISSUE THREAD

**Issue by jenow** [abhimortal6/simple_s3#22]
An error occurs while building after adding the config in `app/build.gradle` with proguard thingy for release build:

app/build.gradle buildTypes config:

```groovy
    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
            minifyEnabled true
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-aws-2.1.5.pro'
        }
    }
```

Error:

```
A problem occurred evaluating project ':app'.
> No signature of method: build_ajc2ccfl7mvlzb5r4jy7yjnzb.android() is applicable for argument types:
 (build_ajc2ccfl7mvlzb5r4jy7yjnzb$_run_closure2) values: [build_ajc2ccfl7mvlzb5r4jy7yjnzb$_run_closure2@42958fa8]
```

**Comment by anushkapubudu** [comment]
did you found any solution to that?

**Comment by jenow** [comment]
> did you found any solution to that?

Not yet unfortunately.

**Comment by sudhirgamit** [comment]
buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
            minifyEnabled true
            // useProguard true <--comment this line
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-aws-2.1.5.pro'
        }
    }

Solve This Issues..

**Comment by sudhirgamit** [comment]
// useProguard true <-- Comment This Line And Solved Your Issues.

**Comment by sudhirgamit** [comment]
> An error occurs while building after adding the config in `app/build.gradle` with proguard thingy for release build:
> 
> app/build.gradle buildTypes config:
> 
> ```groovy
>     buildTypes {
>         release {
>             // TODO: Add your own signing config for the release build.
>             // Signing with the debug keys for now, so `flutter run --release` works.
>             signingConfig signingConfigs.debug
>             minifyEnabled true
>             useProguard true
>             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-aws-2.1.5.pro'
>         }
>     }
> ```
> 
> Error:
> 
> ```
> A problem occurred evaluating project ':app'.
> > No signature of method: build_ajc2ccfl7mvlzb5r4jy7yjnzb.android() is applicable for argument types:
>  (build_ajc2ccfl7mvlzb5r4jy7yjnzb$_run_closure2) values: [build_ajc2ccfl7mvlzb5r4jy7yjnzb$_run_closure2@42958fa8]
> ```

// useProguard true

Comment This Line And Solve Your Issue.

**Comment by jenow** [comment]
> > An error occurs while building after adding the config in `app/build.gradle` with proguard thingy for release build:
> > app/build.gradle buildTypes config:
> > ```groovy
> >     buildTypes {
> >         release {
> >             // TODO: Add your own signing config for the release build.
> >             // Signing with the debug keys for now, so `flutter run --release` works.
> >             signingConfig signingConfigs.debug
> >             minifyEnabled true
> >             useProguard true
> >             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-aws-2.1.5.pro'
> >         }
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Error:
> > ```
> > A problem occurred evaluating project ':app'.
> > > No signature of method: build_ajc2ccfl7mvlzb5r4jy7yjnzb.android() is applicable for argument types:
> >  (build_ajc2ccfl7mvlzb5r4jy7yjnzb$_run_closure2) values: [build_ajc2ccfl7mvlzb5r4jy7yjnzb$_run_closure2@42958fa8]
> > ```
> 
> // useProguard true
> 
> Comment This Line And Solve Your Issue.

Right, it works on release without the proguard even though it says otherwise in the documentation.
Thanks.
