### ISSUE TITLE
Static method 'uploadFile' can't be accessed through an instance

### ISSUE THREAD

**Issue by unluckyxiii** [abhimortal6/simple_s3#7]
Hi. I was looking around for solution to upload images to S3 and found your package interesting. I opened your example and received the error message "Static method 'uploadFile' can't be accessed through an instance" at line 107 of your main.dart, before I can run and test it. Could you advice on this? Thanks.

<img width="451" alt="Screenshot 2021-06-29 at 1 00 18 PM" src="https://user-images.githubusercontent.com/586487/123740205-a2c19d80-d8da-11eb-88d5-687f2c3c17f1.png">

**Comment by abhimortal6** [comment]
Hi please check the version you are on it should be 0.3.2. If you're using an older version then use the example of that version your example and plugin version is mismatching.

**Comment by unluckyxiii** [comment]
got it working thanks.
